[project]
name = "backend-starter-app"
description = "A barebones python app"
version = "0.0.1"
dependencies = [
    "django",
    "psycopg2",
    "pre-commit",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
